[package]
name = "id-connectors"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
argon2 = "0.5"
password-hash = "0.5"
rand = "0.8"

ldap3 = "0.11"
