[server]
bind = "0.0.0.0:1812"
shared_secret = "env:CERBERE_RADIUS_SECRET"
concurrency = 1024
hot_reload = true

[backend.primary]
type = "file"
url = "ldaps://ldap.example.com:636"
bind_dn = "cn=bind,dc=example,dc=com"
bind_password = "env:LDAP_BIND_PWD"
user_base_dn = "ou=users,dc=example,dc=com"
group_base_dn = "ou=groups,dc=example,dc=com"
