[package]
name = "radius-core"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["rt-multi-thread","macros","net"] }
tracing = "0.1"
policy-engine = { path = "../policy-engine" }
